### ISSUE TITLE
UI blurry on some computers

### ISSUE THREAD

**Issue by ghost** [the-pineapple-man/File-Roulette#1]
On some computers the ui is blurry

Place this code at the beginning to fix

```
from ctypes import windll

windll.shcore.SetProcessDpiAwareness(1)
```
before fix

<img width="299" alt="image" src="https://github.com/the-pineapple-man/File-Roulette/assets/160193048/b3bd668a-8f17-4d7b-a575-c861f0180f44">

after fix

<img width="194" alt="Screenshot 2024-03-22 210743" src="https://github.com/the-pineapple-man/File-Roulette/assets/160193048/36e2f548-51f5-45f0-b8d9-60964154b7df">

Edit: the reason why is because of the scale and layout setting. The more it is the blurrier your thing becomes if you don't add this code

**Comment by ghost** [comment]
Fix this it should take you 2 seconds not 2 days

**Comment by the-pineapple-man** [comment]
@chicken-muggets fuck you
